require 'chef/provisioning'
require 'chef/provisioning/digitalocean_driver/version'
require 'chef/provisioning/digitalocean_driver/driver'

require 'chef/resource/digitalocean_droplet'
require 'chef/resource/digitalocean_domain_record'
require 'chef/resource/digitalocean_domain'
require 'chef/resource/digitalocean_floating_ip'
require 'chef/resource/digitalocean_image'
require 'chef/resource/digitalocean_snapshot'
require 'chef/resource/digitalocean_ssh_key'
require 'chef/resource/digitalocean_tag'
require 'chef/resource/digitalocean_volume'
